services:
  redis-node-1:
    image: "redis:latest"
    container_name: "redis_node_1"
    command: redis-server --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --cluster-announce-ip redis-node-1
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    ports:
      - "8001:6379"
      - "18001:16379"
    networks:
      - redis-cluster

  redis-node-2:
    image: "redis:latest"
    container_name: "redis_node_2"
    command: redis-server --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --cluster-announce-ip redis-node-2
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    ports:
      - "8002:6379"
      - "18002:16379"
    networks:
      - redis-cluster

  redis-node-3:
    image: "redis:latest"
    container_name: "redis_node_3"
    command: redis-server --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --cluster-announce-ip redis-node-3
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    ports:
      - "8003:6379"
      - "18003:16379"
    networks:
      - redis-cluster

  redis-node-4:
    image: "redis:latest"
    container_name: "redis_node_4"
    command: redis-server --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --cluster-announce-ip redis-node-4
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    ports:
      - "8004:6379"
      - "18004:16379"
    networks:
      - redis-cluster

  redis-node-5:
    image: "redis:latest"
    container_name: "redis_node_5"
    command: redis-server --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --cluster-announce-ip redis-node-5
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    ports:
      - "8005:6379"
      - "18005:16379"
    networks:
      - redis-cluster

  redis-node-6:
    image: "redis:latest"
    container_name: "redis_node_6"
    command: redis-server --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --cluster-announce-ip redis-node-6
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    ports:
      - "8006:6379"
      - "18006:16379"
    networks:
      - redis-cluster

  redis-node-7:
    image: "redis:latest"
    container_name: "redis_node_7"
    command: redis-server --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --cluster-announce-ip redis-node-7
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    ports:
      - "8007:6379"
      - "18007:16379"
    networks:
      - redis-cluster

  redis-node-8:
    image: "redis:latest"
    container_name: "redis_node_8"
    command: redis-server --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --cluster-announce-ip redis-node-8
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    ports:
      - "8008:6379"
      - "18008:16379"
    networks:
      - redis-cluster

  redis-node-9:
    image: "redis:latest"
    container_name: "redis_node_9"
    command: redis-server --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
      --cluster-announce-ip redis-node-9
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    ports:
      - "8009:6379"
      - "18009:16379"
    networks:
      - redis-cluster

  redis-cluster-init:
    image: "redis:latest"
    container_name: "redis_cluster_init"
    command: >
      /bin/sh -c '
        echo "Waiting for Redis nodes..." &&
        sleep 15 &&
        redis-cli --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379 redis-node-8:6379 redis-node-9:6379 --cluster-replicas 2 --cluster-yes &&
        echo "Waiting for cluster to stabilize..." &&
        sleep 5 &&
        redis-cli -h redis-node-1 cluster info &&
        redis-cli -h redis-node-1 cluster nodes &&
        echo "Cluster initialization complete"
      '
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
      - redis-node-7
      - redis-node-8
      - redis-node-9
    networks:
      - redis-cluster

  mongodb:
    image: "mongo:latest"
    container_name: "mongodb_container"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - redis-cluster

volumes:
  redis_data_1:
  redis_data_2:
  redis_data_3:
  redis_data_4:
  redis_data_5:
  redis_data_6:
  redis_data_7:
  redis_data_8:
  redis_data_9:
  mongodb_data:

networks:
  redis-cluster:
    driver: bridge
